### ISSUE TITLE
memory limit error

### ISSUE THREAD

**Issue by jury89** [wookieb/relative-date#1]
Hi,

running the command 

`composer require wookieb/relative-date`

i get this error error
```
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 220

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 220

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```

I fixed it specifying the version to install 
`composer require wookieb/relative-date:0.1`

Cheers,
Jury

**Comment by wookieb** [comment]
Hi

I doubt this is an error related to my package since it's super small and without dependencies.
Please follow the guide from the docs https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors
