### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by buddhaCode** [wookieb/relative-date#2]
Hi Lukas,
thanks for your great lib. I really like it. Unfortunately, i got an error using a translator. I get:

> [X] days ago

using:
```
$translator = new \Symfony\Component\Translation\Translator('de_DE');
$formatter = new \Wookieb\RelativeDate\Formatters\TranslatorFormatter($translator);
$calculator = \Wookieb\RelativeDate\Calculators\TimeAgoDateDiffCalculator::full();
```

Any idea why? The BasicFormatter works just fine.

**Comment by wookieb** [comment]
Hi.
See code from bundle https://github.com/wookieb/relative-date-bundle

You need to have a domain "relative-date" for translations.
Here is example translation file https://github.com/wookieb/relative-date-bundle/blob/master/Resources/translations/relative-date.pl.yml

**Comment by buddhaCode** [comment]
Thanks, works fine!
